export const networks = {
    juno: {
        chain_id: "juno-1",
        chain_name: "juno",
        coingecko: "juno-network",
        api: [
            "https://api-juno-ia.cosmosia.notional.ventures",
            "https://juno-api.polkachu.com",
            "https://lcd-juno.itastakers.com",
        ],
        rpc: [
            "https://rpc-juno-ia.cosmosia.notional.ventures:443",
            "https://juno-rpc.polkachu.com:443",
            "https://rpc-juno.itastakers.com:443",
            "https://rpc-juno.itastakers.com:443",
        ],
        snapshot_provider: "",
        sdk_version: "0.45.8",
        coin_type: "118",
        min_tx_fee: "3000",
        addr_prefix: "juno",
        logo: "/logos/juno.png",
        assets: [
            {
                base: "ujuno",
                symbol: "JUNO",
                exponent: "6",
                coingecko_id: "juno-network",
                logo: "/logos/juno.png",
            },
        ],
    },
    omniflix: {
        chain_id: "omniflixhub-1",
        chain_name: "OmniFlix Hub",
        coingecko: "omniflix-network",
        api: ["https://rest.omniflix.network"],
        rpc: ["https://rpc-juno.itastakers.com"],
        snapshot_provider: "",
        sdk_version: "0.46.1",
        coin_type: 118,
        min_tx_fee: "3000",
        addr_prefix: "omniflix",
        logo: "/logos/omniflix.png",
        assets: [
            {
                base: "uflix",
                symbol: "FLIX",
                exponent: 6,
                coingecko_id: "omniflix-network",
                logo: "/logos/omniflix.png",
            },
        ],
    },
    core: {
        chain_id: "coreum-devnet-1",
        chain_name: "Coreum Devnet 1",
        coingecko: "coreum",
        api: ["https://s-0.devnet-1.coreum.dev/rest/"],
        rpc: ["https://s-0.devnet-1.coreum.dev/"],
        snapshot_provider: "",
        sdk_version: "0.46.1",
        coin_type: "990",
        min_tx_fee: "800",
        addr_prefix: "devcore",
        logo: "/logos/core.jpg",
        assets: [
            {
                base: "ducore",
                symbol: "RIZE",
                exponent: "6",
                coingecko_id: "coreum",
                logo: "/logos/coreum.jpg",
            },
        ],
    },
    osmosis: {
        chain_id: "osmosis-1",
        chain_name: "osmosis",
        coingecko: "osmosis",
        api: [
            "https://api-osmosis-ia.cosmosia.notional.ventures",
            "https://osmosis-api.polkachu.com",
            "https://osmo.api.ping.pub",
            "https://lcd-osmosis.blockapsis.com",
        ],
        rpc: [
            "https://rpc-osmosis-ia.cosmosia.notional.ventures:443",
            "https://osmosis-rpc.polkachu.com:443",
            "https://osmosis.validator.network:443",
            "https://rpc-osmosis.blockapsis.com:443",
        ],
        snapshot_provider: "",
        sdk_version: "0.46.1",
        coin_type: "118",
        min_tx_fee: "800",
        addr_prefix: "osmo",
        logo: "/logos/osmosis.jpg",
        assets: [
            {
                base: "uosmo",
                symbol: "OSMO",
                exponent: "6",
                coingecko_id: "osmosis",
                logo: "/logos/osmosis.jpg",
            },
            {
                base: "uion",
                symbol: "ION",
                exponent: "6",
                coingecko_id: "ion",
                logo: "/logos/osmosis.jpg",
            },
            {
                base: "usomm",
                symbol: "SOMM",
                exponent: "6",
                coingecko_id: "somm",
                logo: "",
            },
        ],
    },
    stargaze: {
        chain_id: "stargaze-1",
        chain_name: "stargaze",
        api: [
            "https://stargaze-api.polkachu.com/",
            "https://api-stargaze-ia.cosmosia.notional.ventures/",
            "https://rest.stargaze-apis.com",
            "https://rest.stargaze.publicawesome.dev",
        ],
        rpc: [
            "https://stargaze-rpc.polkachu.com/",
            "https://rpc-stargaze-ia.cosmosia.notional.ventures/",
            "https://rpc.stargaze-apis.com:443",
            "https://rpc.stargaze.ezstaking.io:443",
        ],
        snapshot_provider: "",
        sdk_version: "0.45.6",
        coin_type: "118",
        min_tx_fee: "800",
        addr_prefix: "stars",
        logo: "/logos/stargaze.png",
        assets: [
            {
                base: "ustars",
                symbol: "STARS",
                exponent: "6",
                coingecko_id: "stargaze",
                logo: "/logos/stargaze.png",
            },
        ],
    },
    teritori: {
        chain_id: "teritori-1",
        chain_name: "teritori",
        api: [
            "https://rest.mainnet.teritori.com",
            "https://api.teritori.nodestake.top",
        ],
        rpc: [
            "https://rpc.mainnet.teritori.com",
            "https://rpc.teritori.nodestake.top",
        ],
        snapshot_provider: "",
        sdk_version: "0.45.4",
        coin_type: "118",
        min_tx_fee: "5000",
        addr_prefix: "tori",
        logo: "/logos/teritori.svg",
        assets: [
            {
                base: "utori",
                symbol: "TORI",
                exponent: "6",
                coingecko_id: "teritori",
                logo: "/logos/teritori.svg",
            },
        ],
    },
};
